### ISSUE TITLE
ReScript syntax

### ISSUE THREAD

**Issue by vmarcosp** [yawaramin/bucklescript-bindings-cookbook#4]
First of all, thanks for your work on this cookbook! This is awesome.

I want to know if you're planning to update this project to the new ReScript syntax or if you want to keep the reason syntax and use this repository as a `melange-cookbook` (or something like that 😂 ). I'm asking because I want to help you to update this project to use ReScript syntax, but I respect and understand if you prefer to keep the reason syntax. 

If you want to keep using reason syntax, I would be happy if you let me fork this (keeping your commits and the authorship) and create a `rescript-bindings-cookbook`.

**Comment by yawaramin** [comment]
Hi, thank you :-) ReScript syntax is currently in https://github.com/yawaramin/bucklescript-bindings-cookbook/blob/master/ReScript.md thanks to @tom-sherman 

You are welcome to suggest improvements!
